### ISSUE TITLE
會場地圖的說明欄位顯示不正常 (Safari 16.4)

### ISSUE THREAD

**Issue by mirumodapon** [sitcon-tw/2024#28]
<img width="1171" alt="截圖 2024-02-27 下午6 14 34" src="https://github.com/sitcon-tw/2024/assets/66897537/63de7221-74d3-416e-81e4-f8d1bee29da7">

**Comment by gnehs** [comment]
<img width="1689" alt="image" src="https://github.com/sitcon-tw/2024/assets/16719720/2cb1650a-3f2a-4bd4-a773-16f78771e83e">
我的 Safari 17.3 很乖

**Comment by gnehs** [comment]
![image](https://github.com/sitcon-tw/2024/assets/16719720/8abb3615-6a24-44f1-98dc-32aebefc5e4d)

Safari 17 修正了這個問題
https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes

**Comment by mirumodapon** [comment]
好的！感謝你～
